Repository OPCFoundation/UA-CloudLibrary, pull requests merged in 2022-03, with the labels that each got.

#73 Switch to GET for find REST method.
  SampleConsoleClient/Program.cs
  UACloudLibraryServer/Controllers/InfoModelController.cs
Labels: bug

#75 Enable download counter, use dates from nodeset file and a bug fix in…
  UACloudLibraryServer/Controllers/InfoModelController.cs
  UACloudLibraryServer/Interfaces/IDatabase.cs
  UACloudLibraryServer/Models/InfoModel.cs
  UACloudLibraryServer/PostgreSQLDB.cs
Labels: enhancement

#69 Dev run in three steps
  .github/workflows/dotnet.yml
  README.md
  UA-CloudLibrary.sln
  UACloudLibraryServer/EmailSender.cs
  UACloudLibraryServer/GraphQL/AppDbContext.cs
  UACloudLibraryServer/PostgreSQLDB.cs
  UACloudLibraryServer/Startup.cs
  UACloudLibraryServer/UA-CloudLibrary.csproj
  docker-compose.dcproj
  docker-compose.override.yml
  docker-compose.yml
  launchSettings.json
  local-dev-docker/docker_pgadmin_servers.json
Labels: documentation, enhancement
